import { useState, type FormEvent } from 'react'
import { Download, Upload, Trash2 } from 'lucide-react'
import { api, APIError } from '../api/client'
import { useApi } from '../hooks/useApi'
import type { Server } from '../types'
import type { RuleProfile, RuleProfilesResponse } from '../types/rule-profiles'
import { Empty, ErrorState, Loading } from './Status'
import { Notice, SectionHeader } from './UI'

export function RuleProfilesSettings() {
  const profiles=useApi(()=>api.get<RuleProfilesResponse>('/rule-profiles'),[]), servers=useApi(()=>api.get<Server[]>('/servers'),[])
  const [json,setJSON]=useState(''),[message,setMessage]=useState(''),[scopeType,setScopeType]=useState('global'),[scopeValue,setScopeValue]=useState('')
  if(profiles.loading||servers.loading)return <Loading/>; if(profiles.error||servers.error)return <ErrorState error={(profiles.error??servers.error)!} retry={()=>{void profiles.reload();void servers.reload()}}/>
  async function importProfile(e:FormEvent){e.preventDefault();try{const parsed=JSON.parse(json) as RuleProfile;await api.post('/rule-profiles',{name:parsed.name,description:parsed.description??'',entries:parsed.entries});setJSON('');setMessage('Rule profile imported.');void profiles.reload()}catch(reason){setMessage(reason instanceof APIError?`${reason.message}: ${reason.detail}`:'Invalid profile JSON')}}
  if (!profiles.data || Array.isArray(profiles.data)) return null
  function download(p:RuleProfile){const blob=new Blob([JSON.stringify({format:'pgsentinel-rule-profile/v1',name:p.name,description:p.description,entries:p.entries},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${p.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.json`;a.click();URL.revokeObjectURL(url)}
  async function apply(p:RuleProfile){try{const value=scopeType==='global'?'':scopeValue;const preview=await api.post<{conflicts:string[]}>(`/rule-profiles/${p.id}/apply`,{scopeType,scopeValue:value,reason:`Applied profile ${p.name}`,preview:true});const replace=preview.conflicts.length?confirm(`Replace ${preview.conflicts.length} conflicting override(s)?`):false;if(preview.conflicts.length&&!replace)return;await api.post(`/rule-profiles/${p.id}/apply`,{scopeType,scopeValue:value,reason:`Applied profile ${p.name}`,replace});setMessage(`Applied ${p.name}.`)}catch(reason){setMessage(reason instanceof APIError?`${reason.message}: ${reason.detail}`:'Unable to apply profile')}}
  return <section id="rule-profiles"><SectionHeader title="Rule profiles" description="Import, export, preview, and apply reviewed analyzer threshold sets."/><form className="settings-form" onSubmit={importProfile}><label>Profile JSON<textarea required rows={7} value={json} onChange={e=>setJSON(e.target.value)} placeholder='{"name":"OLTP","entries":[{"ruleId":"blocking-queries","value":30}]}'/></label><div className="form-actions"><button className="button secondary"><Upload/> Import profile</button></div></form><div className="form-grid two"><label>Apply scope<select value={scopeType} onChange={e=>{setScopeType(e.target.value);setScopeValue('')}}><option value="global">Global</option><option value="server">Server</option><option value="tag">Tag</option></select></label>{scopeType==='server'?<label>Server<select required value={scopeValue} onChange={e=>setScopeValue(e.target.value)}><option value="">Select server</option>{servers.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>:scopeType==='tag'?<label>Tag<input required value={scopeValue} onChange={e=>setScopeValue(e.target.value)}/></label>:null}</div>{profiles.data?.items.length===0?<Empty title="No rule profiles" detail="Import a reviewed profile to reuse analyzer thresholds."/>:<div className="route-list">{profiles.data?.items.map(p=><article key={p.id}><div><strong>{p.name}</strong><span>{p.description||'No description'} · {p.entries.length} rules</span></div><button className="button secondary compact" disabled={scopeType!=='global'&&!scopeValue} onClick={()=>void apply(p)}>Apply</button><button className="icon-button" aria-label={`Export ${p.name}`} onClick={()=>download(p)}><Download/></button><button className="icon-button danger" aria-label={`Delete ${p.name}`} onClick={async()=>{if(confirm(`Delete ${p.name}?`)){await api.delete(`/rule-profiles/${p.id}`);void profiles.reload()}}}><Trash2/></button></article>)}</div>}{message&&<Notice>{message}</Notice>}</section>
}
