import { FormEvent, useState } from 'react'
import { Bell, CalendarClock, Download, History, Route, Save, Send, SlidersHorizontal, Trash2 } from 'lucide-react'
import { api, APIError } from '../api/client'
import { Empty, ErrorState, Loading } from '../components/Status'
import { Notice, PageHeader, SectionHeader } from '../components/UI'
import { useApi } from '../hooks/useApi'
import type { Server } from '../types'
import type { NotificationDelivery, NotificationDestination, NotificationRoute } from '../types/notifications'
import { OperatorControlsSettings } from '../components/OperatorControlsSettings'
import { ChangeHistorySettings } from '../components/ChangeHistorySettings'
import { RuleProfilesSettings } from '../components/RuleProfilesSettings'

const severities = ['INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
const transitions = ['new', 'severity_increased', 'reopened', 'resolved']
const split = (value: string) => value.split(',').map(item => item.trim()).filter(Boolean)

export function SettingsPage() {
  const destinations = useApi(() => api.get<NotificationDestination[]>('/notifications'), [])
  const routes = useApi(() => api.get<NotificationRoute[]>('/notification-routes'), [])
  const deliveries = useApi(() => api.get<NotificationDelivery[]>('/notification-deliveries?limit=50'), [])
  const servers = useApi(() => api.get<Server[]>('/servers'), [])
  const [provider, setProvider] = useState('ntfy')
  const [name, setName] = useState('')
  const [form, setForm] = useState({ serverUrl: 'https://ntfy.sh', topic: '', token: '', username: '', password: '', webhookUrl: '' })
  const [status, setStatus] = useState('')
  const [route, setRoute] = useState({ name: '', priority: 100, severities: ['HIGH', 'CRITICAL'], categories: '', serverIds: [] as string[], serverTags: '', transitions: ['new', 'severity_increased', 'reopened'], destinationIds: [] as string[], cooldownSeconds: 0 })
  const payload = { name, provider, enabled: true, ...form }
  const failed = destinations.error || routes.error || deliveries.error || servers.error
  async function test(event: FormEvent) { event.preventDefault(); setStatus('Sending test notification…'); try { await api.post('/notifications/test', payload); setStatus('Test notification delivered successfully.') } catch (reason) { setStatus(reason instanceof APIError ? `${reason.message}: ${reason.detail}` : 'Notification failed') } }
  async function saveDestination() { setStatus('Saving destination…'); try { await api.post('/notifications', payload); setName(''); setStatus('Notification destination saved securely.'); void destinations.reload() } catch (reason) { setStatus(reason instanceof APIError ? `${reason.message}: ${reason.detail}` : 'Unable to save destination') } }
  async function saveRoute(event: FormEvent) { event.preventDefault(); setStatus('Saving routing rule…'); try { await api.post('/notification-routes', { ...route, enabled: true, categories: split(route.categories), serverTags: split(route.serverTags) }); setRoute({ ...route, name: '', destinationIds: [] }); setStatus('Routing rule saved.'); void routes.reload() } catch (reason) { setStatus(reason instanceof APIError ? `${reason.message}: ${reason.detail}` : 'Unable to save routing rule') } }
  async function toggleRoute(item: NotificationRoute) { setStatus(`${item.enabled ? 'Disabling' : 'Enabling'} routing rule…`); try { await api.put(`/notification-routes/${item.id}`, { name: item.name, enabled: !item.enabled, priority: item.priority, severities: item.severities, categories: item.categories, serverIds: item.serverIds, serverTags: item.serverTags, transitions: item.transitions, destinationIds: item.destinationIds, cooldownSeconds: item.cooldownSeconds }); setStatus(`Routing rule ${item.enabled ? 'disabled' : 'enabled'}.`); void routes.reload() } catch (reason) { setStatus(reason instanceof APIError ? `${reason.message}: ${reason.detail}` : 'Unable to update routing rule') } }
  async function downloadDiagnostics() { setStatus('Preparing redacted diagnostic bundle…'); try { const result = await api.download('/diagnostic-bundle'); const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = result.filename; link.click(); URL.revokeObjectURL(url); setStatus('Diagnostic bundle downloaded. Review it before sharing.') } catch (reason) { setStatus(reason instanceof APIError ? `${reason.message}: ${reason.detail}` : 'Unable to export diagnostic bundle') } }
  const toggle = (field: 'severities' | 'transitions' | 'serverIds' | 'destinationIds', value: string) => setRoute(current => ({ ...current, [field]: current[field].includes(value) ? current[field].filter(item => item !== value) : [...current[field], value] }))
  if (destinations.loading || routes.loading || deliveries.loading || servers.loading) return <Loading />
  if (failed) return <ErrorState error={failed} retry={() => { void destinations.reload(); void routes.reload(); void deliveries.reload(); void servers.reload() }} />
  return <><PageHeader title="Settings" description="Configure notifications and safe controls for expected PostgreSQL conditions." />
    <div className="settings-layout"><aside className="settings-nav"><a href="#destinations"><Bell />Destinations</a><a href="#routing"><Route />Routing</a><a href="#change-history"><History />Change history</a><a href="#maintenance"><CalendarClock />Maintenance</a><a href="#thresholds"><SlidersHorizontal />Thresholds</a><a href="#delivery-history"><History />Delivery history</a><a href="#diagnostics"><Download />Diagnostics</a></aside><div className="settings-content">
      <section id="destinations"><SectionHeader title="Notification destinations" description="Send findings to an existing ntfy topic or webhook endpoint." /><form className="settings-form" onSubmit={test}><div className="form-grid two"><label>Display name<input required value={name} onChange={event => setName(event.target.value)} placeholder="Database operations" /></label><label>Provider<select value={provider} onChange={event => setProvider(event.target.value)}><option value="ntfy">ntfy</option><option value="webhook">Generic webhook</option></select></label></div>{provider === 'ntfy' ? <div className="form-stack"><label>Server URL<input className="mono" type="url" required value={form.serverUrl} onChange={event => setForm({ ...form, serverUrl: event.target.value })} /></label><label>Topic<input className="mono" required value={form.topic} onChange={event => setForm({ ...form, topic: event.target.value })} /></label><div className="form-grid two"><label>Access token <small>Optional</small><input type="password" value={form.token} onChange={event => setForm({ ...form, token: event.target.value })} /></label><label>Username <small>Optional</small><input value={form.username} onChange={event => setForm({ ...form, username: event.target.value })} /></label></div><label>Password <small>Optional</small><input type="password" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /></label></div> : <label>Webhook URL<input className="mono" type="url" required value={form.webhookUrl} onChange={event => setForm({ ...form, webhookUrl: event.target.value })} /></label>}<div className="form-actions"><button type="button" className="button secondary" onClick={() => void saveDestination()}><Save /> Save destination</button><button type="submit" className="button primary"><Send /> Send test</button></div></form>
        {destinations.data?.length === 0 ? <Empty title="No notification destinations" detail="Configure a destination before creating routing rules." /> : <div className="destination-list">{destinations.data?.map(destination => <article key={destination.id}><span className="destination-icon"><Bell /></span><div><strong>{destination.name}</strong><span>{destination.provider} · {destination.enabled ? 'Enabled' : 'Disabled'}</span></div><button className="icon-button danger" aria-label={`Delete ${destination.name}`} title="Delete destination" onClick={async () => { if (confirm(`Delete ${destination.name}? Existing routes will stop using it.`)) { await api.delete(`/notifications/${destination.id}`); void destinations.reload(); void routes.reload() } }}><Trash2 /></button></article>)}</div>}
      </section>
      <section id="routing"><SectionHeader title="Routing rules" description="All selected filters must match. Empty filters match any value; matching routes are combined without duplicate delivery." /><form className="settings-form" onSubmit={saveRoute}><div className="form-grid two"><label>Rule name<input required value={route.name} maxLength={100} onChange={event => setRoute({ ...route, name: event.target.value })} placeholder="Critical production findings" /></label><label>Priority<input type="number" min="0" max="1000" value={route.priority} onChange={event => setRoute({ ...route, priority: Number(event.target.value) })} /></label></div><fieldset><legend>Severity <small>Optional</small></legend><div className="check-grid">{severities.map(value => <label key={value}><input type="checkbox" checked={route.severities.includes(value)} onChange={() => toggle('severities', value)} />{value}</label>)}</div></fieldset><fieldset><legend>Lifecycle transition <small>Optional</small></legend><div className="check-grid">{transitions.map(value => <label key={value}><input type="checkbox" checked={route.transitions.includes(value)} onChange={() => toggle('transitions', value)} />{value.replaceAll('_', ' ')}</label>)}</div></fieldset><div className="form-grid two"><label>Categories <small>Comma separated, optional</small><input value={route.categories} onChange={event => setRoute({ ...route, categories: event.target.value })} placeholder="replication, wal" /></label><label>Server tags <small>Any matching tag, optional</small><input value={route.serverTags} onChange={event => setRoute({ ...route, serverTags: event.target.value })} placeholder="production, dba" /></label></div><fieldset><legend>Servers <small>Optional</small></legend><div className="check-grid">{servers.data?.map(server => <label key={server.id}><input type="checkbox" checked={route.serverIds.includes(server.id)} onChange={() => toggle('serverIds', server.id)} />{server.name}</label>)}</div></fieldset><fieldset><legend>Destinations <small>Required</small></legend><div className="check-grid">{destinations.data?.filter(item => item.enabled).map(destination => <label key={destination.id}><input type="checkbox" checked={route.destinationIds.includes(destination.id)} onChange={() => toggle('destinationIds', destination.id)} />{destination.name}</label>)}</div></fieldset><label>Cooldown in seconds <small>0 disables cooldown; maximum 86400</small><input type="number" min="0" max="86400" value={route.cooldownSeconds} onChange={event => setRoute({ ...route, cooldownSeconds: Number(event.target.value) })} /></label><div className="form-actions"><button className="button primary" disabled={route.destinationIds.length === 0}><Save /> Save routing rule</button></div></form>
        {routes.data?.length === 0 ? <Empty title="No routing rules" detail="Until a rule is created, High and Critical lifecycle events go to every enabled destination." /> : <div className="route-list">{routes.data?.map(item => <article key={item.id}><div><strong>{item.name}</strong><span>{item.enabled ? 'Enabled' : 'Disabled'} · Priority {item.priority} · {item.severities.length ? item.severities.join(', ') : 'all severities'} · {item.destinationIds.length} destination(s){item.cooldownSeconds ? ` · ${item.cooldownSeconds}s cooldown` : ''}</span></div><button type="button" className="button secondary compact" onClick={() => void toggleRoute(item)}>{item.enabled ? 'Disable' : 'Enable'}</button><button className="icon-button danger" aria-label={`Delete ${item.name}`} onClick={async () => { if (confirm(`Delete routing rule ${item.name}?`)) { await api.delete(`/notification-routes/${item.id}`); void routes.reload() } }}><Trash2 /></button></article>)}</div>}
      </section>
      <section id="delivery-history"><SectionHeader title="Delivery history" description="The latest 50 delivery attempts. Retry errors are redacted and credentials are never shown." />{deliveries.data?.length === 0 ? <Empty title="No delivery history" detail="Lifecycle notifications will appear here after findings match a route." /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>Created</th><th>Finding</th><th>Destination</th><th>Transition</th><th>Result</th><th>Attempts</th></tr></thead><tbody>{deliveries.data?.map(item => <tr key={`${item.eventId}-${item.destinationId}`}><td>{new Date(item.createdAt).toLocaleString()}</td><td><strong>{item.findingTitle}</strong><small>{item.serverName || item.serverId} · {item.severity} · {item.category}</small></td><td>{item.destinationName || 'Deleted destination'}</td><td>{item.eventType.replaceAll('_', ' ')}</td><td><span className={`delivery-status ${item.status}`}>{item.status}</span>{item.lastError && <small title={item.lastError}>{item.lastError}</small>}</td><td>{item.attempts}</td></tr>)}</tbody></table></div>}</section>
      <OperatorControlsSettings />
      <RuleProfilesSettings />
      <ChangeHistorySettings />
      <section id="diagnostics"><SectionHeader title="Diagnostic bundle" description="Export bounded support evidence without database credentials, server addresses, connection details, or raw SQL text." /><p className="muted">The ZIP contains build metadata, redacted server status, up to 1,000 findings, and collection freshness. Always review it before sharing.</p><div className="form-actions"><button type="button" className="button secondary" onClick={() => void downloadDiagnostics()}><Download /> Download diagnostic bundle</button></div></section>
      {status && <Notice>{status}</Notice>}
    </div></div>
  </>
}
